server {
    listen 80;
    client_max_body_size 132m;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(register|login|logout|me|links|files|questions|ask-question) {
        proxy_pass http://api:5000;
        proxy_set_header Host $host;
        proxy_read_timeout 120s;
    }
}
